version: '3'
services:
  web:
    build: .
    ports:
      - "3031:3031"
    restart: always
    volumes:
      - data:/data

  redis:
    image: "redis:alpine"
    restart: always

volumes:
  data:
